"""start_date <= end_date constaint

Revision ID: 7f84e6f9fd6f
Revises: b70e4e1f8862
Create Date: 2023-03-14 03:02:12.486168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f84e6f9fd6f'
down_revision = 'b70e4e1f8862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
