"""Vacation model and relationship

Revision ID: f7186c348c68
Revises: 27bf2aa3b8c7
Create Date: 2023-03-04 11:44:24.064960

"""
from alembic import op
import sqlalchemy as sa

import app

# revision identifiers, used by Alembic.
revision = 'f7186c348c68'
down_revision = '27bf2aa3b8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacation',
    sa.Column('id', app.model.base.CustomUUID(as_uuid=True), nullable=False),
    sa.Column('employee_id', app.model.base.CustomUUID(as_uuid=True), nullable=True),
    sa.Column('vacation_type', sa.Enum('paid_leave', 'unpaid_leave', name='vacationtypes'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacation_id'), 'vacation', ['id'], unique=False)
    op.alter_column('employee', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employee', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_vacation_id'), table_name='vacation')
    op.drop_table('vacation')
    # ### end Alembic commands ###
