"""Cascade all,delete for relationships

Revision ID: fa2b0fb44f72
Revises: fd69165cee5f
Create Date: 2023-03-13 23:51:43.367687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2b0fb44f72'
down_revision = 'fd69165cee5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
