"""Vacation Types and Balances

Revision ID: fd69165cee5f
Revises: c544964d931a
Create Date: 2023-03-13 02:01:11.242181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd69165cee5f'
down_revision = 'c544964d931a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
