"""2: Cascade all,delete for relationships

Revision ID: ffd12f1a3a13
Revises: fa2b0fb44f72
Create Date: 2023-03-14 00:03:00.360311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd12f1a3a13'
down_revision = 'fa2b0fb44f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
